company = input("enter your company name")
street = input("enter your street address")
city = input("enter your city, province and zip code")
country = input("enter your country")
print("Jordan So")
print(company)
print(street)
print(city)
print(country)
